# Generated by Django 5.0.6 on 2025-04-25 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_fit',
            field=models.CharField(blank=True, choices=[('slim', 'Slim Fit'), ('regular', 'Regular Fit'), ('relaxed', 'Relaxed Fit'), ('loose', 'Loose Fit')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_department',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
