# Generated by Django 5.0.6 on 2025-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_delivery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
