# Generated by Django 5.0.6 on 2025-05-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_parent_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_site',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
